name: Test Emulators

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Start Docker Compose services
      run: docker compose up -d
    
    - name: Wait for services to be ready
      run: sleep 30
    
    - name: Run emulator tests
      run: python -m pytest tests/ -v
    
    - name: Show Docker logs on failure
      if: failure()
      run: docker compose logs